### PR TITLE
Add basic TypeScript types

### PR DESCRIPTION
**Pull request by 9inpachi**
Sorry, with #245 earlier today, in a hurray I ended up placing the `browser` field above the other module related fields. This is just to move that field lower and make the readability easier.

### CODE REVIEW

**Comment by 9inpachi** [comment]
Ahan, cool. I didn't notice that comment. Thanks.

Then, I will keep this PR open to push some very basic types setup to make imports by name work in TypeScript. Because `import { build } from 'jsroot/geom';` works but throws an error in TypeScript unless we use `// @ts-ignore`.

**Comment by 9inpachi** [comment]
There are following ways of fixing the types error.

1. Using `node16` as the  `moduleResolution` option in TypeScript. This is able to pick the exported modules from package.json's `exports` field but still shows a warning that the types are not there.
2. Declaring TypeScript modules using "magically available interfaces"/"global types" like I did in this PR. This does not add any actual types but just declares the modules to direct TypeScript that it's a known module without any types.
3. The most thorough way is to generate declaration files for the JavaScript code. This is done with JSDoc that's used to document types in JavaScript code. I gave it a try so it's in the commit history (can be reverted with https://github.com/root-project/jsroot/pull/246/commits/09f2d6c888a7e57fa96e9c62fb569fcc881383e4). It works but there seem to be some wrong types declared through JSDoc like `object` instead of `Object3D` for a three.js object which cause problems when we actually use the API interface.

I implemented the second option since it's the most simplest without any side effects and without any need to change anything on the consumer side.

**Comment by 9inpachi** [comment]
HSF/phoenix#497 needs this to pass the [pipeline](https://github.com/HSF/phoenix/runs/8235852918?check_suite_focus=true) and complete the update.

**Comment by 9inpachi** [comment]
@linev could you please take a look at this?

**Comment by linev** [comment]
Does it work for you?

If yes - I will be able to check it begin of next week.

**Comment by 9inpachi** [comment]
Yes, it does work. I have added a temporary tag (7.2.0-types) on my fork
and I am using that in Phoenix for now to not block us. So there is no
urgency to merge this.

**Comment by 9inpachi** [comment]
@linev it seems that the types are not added to the latest released version. Do you plan to make it a part of the major version release?

**Comment by linev** [comment]
It will be in 7.3.0 version, which I plan to release shortly before next ROOT 6.28 release.
Up to now there is no concrete plans for it.
If necessary, I can backport changes to 7.2 branch and produce 7.2.2 tag.

**Comment by 9inpachi** [comment]
I think it's fine to release it with 7.3.0. I just wanted to confirm.
Thanks.

Best,
Fawad

**Pull request merged**
