### PR TITLE
Use dynamicImport only inside core.mjs

### PR DESCRIPTION
**Pull request by linev**
Do not export it.

### CODE REVIEW

**Comment by linev** [comment]
@9inpachi Are you ok with that changes?

My question also - why not to use import(/* webpackIgnore: true */ module);
As here:

https://github.com/root-project/jsroot/blob/master/modules/gui/HierarchyPainter.mjs#L2661 

Maybe it is better solution instead of introducing `dynamicImport` function?
Also I remove it from `export` statement of `core.mjs`

**Comment by 9inpachi** [comment]
The changes are fine by me. But this won't work with webpack just yet.

> My question also - why not to use import(/* webpackIgnore: true */ module);

Yes, I remember you mentioned that — that'd be all good. But sorry, it slipped my mind. (:

**Comment by 9inpachi** [comment]
Please feel free to make any other changes you want as well. My code wasn't too clean to begin with.

**Comment by linev** [comment]
@9inpachi 
After recent modifications your example https://github.com/9inpachi/jsroot-minimal does not work.
Do you have special plugin which allows to replace code for webpack as for rollup?

**Comment by 9inpachi** [comment]
> Do you have special plugin which allows to replace code for webpack as for rollup?

There will be one but like I mentioned in https://github.com/root-project/jsroot/pull/236#issue-1284764003, We need a solution where we don't need to update the webpack configuration.

**Comment by linev** [comment]
But now it does not work at all.
At least previous version with `process.env.APP_ENV != "browser"` was providing solution. 
I will try following solution: https://selleo.com/til/posts/pvwk0widyi-how-to-exclude-code-from-production-in-build-time

**Comment by 9inpachi** [comment]
I think what we can focus on is updating the fields in package.json so `build/jsroot.js` gets picked up as the entry point by webpack. That's the only thing that's remaining. You should be able to do that by using [`resolve.mainFields`](https://webpack.js.org/configuration/resolve/#resolvemainfields) but I am inclining toward something that doesn't require changes on the consumer/webpack side.

**Comment by linev** [comment]
I merge changes into master and you can try.

I also can add `"browser": "build/jsroot.js" ` into package.json if it can help you.

**Comment by 9inpachi** [comment]
I tried and the current state doesn't work.

> I also can add "browser": "build/jsroot.js" into package.json if it can help you.

Just doing that won't help. As long as we have "type" and "exports" fields in the package.json, webpack always tries to compile the package as an ES module.

I tried a variety of combinations earlier, and only this worked for all (or most) module systems:

```diff
{
-  "type": "module",
+  "browser": "./build/jsroot.js",
  "main": "./build/jsroot.js",
  "module": "./modules/main.mjs",
-  "exports": {
-    ".": "./modules/main.mjs",
-    "./core": "./modules/core.mjs",
-    "./draw": "./modules/draw.mjs",
-    "./io": "./modules/io.mjs",
-    "./tree": "./modules/tree.mjs",
-    "./colors": "./modules/base/colors.mjs",
-    "./hierarchy": "./modules/gui/HierarchyPainter.mjs",
-    "./latex": "./modules/base/latex.mjs",
-    "./geom": "./modules/geom/TGeoPainter.mjs"
-  },
}
```

The only downside I see to this is that full paths have to be used for exported modules.

**Comment by linev** [comment]
Is there test project where I can reproduce problem?

**Comment by 9inpachi** [comment]
I just pushed a new webpack config to https://github.com/9inpachi/jsroot-minimal. That should be a good test project. Just note that we can't change the webpack config any more than that.

**Comment by linev** [comment]
I only can add following lines to webpack.config.ts:

```
  resolve: {
    extensions: [".ts", ".js", ".json"],
    fallback: {
      "fs" : false,
      "crypto": false,
      "zstd-codec": false,
      "zlib": false,
      "stream": false,
      "url": false,
      "path": false,
      "util": false,
      "http": false,
       "https": false,
       "os": false,
       "net" : false,
       "tls": false,
       "assert": false,
       "atob": false,
       "btoa": false,
       "canvas": false,
       "gl": false,
       "jsdom": false,
       "mathjax": false,
       "tmp": false,
       "xhr": false,
       "xhr2": false,
       "child_process": false
    }
  },
```
But it stuck somewhere in initialization and does not executing draw code.
But at least it does not produce any errors when generating `bundle.js`

**Comment by 9inpachi** [comment]
I have no idea why that happens.

I experienced the same thing initially which I mentioned here: https://github.com/root-project/jsroot/issues/233#issuecomment-1156888583

And it seems you made some changes in jsroot master and fixed it then.

**Comment by linev** [comment]
To make it working, I also need to add/modify following entries in webpack config:
```
mode: "production",
  performance: {
    hints: false,
    maxEntrypointSize: 512000,
    maxAssetSize: 512000
  },
  experiments: {
    topLevelAwait: false,
  }
```

Then it works for me

**Comment by 9inpachi** [comment]
Thanks a lot! I will give it a try on my side.

Best,
Fawad

**Comment by 9inpachi** [comment]
Hi @linev,

Sorry for following up on this so late. I just had the time to try it out today and the latest master branch works if I just add this to jsroot's package.json:

```json
"browser": {
  "fs" : false,
  "crypto": false,
  "zstd-codec": false,
  "zlib": false,
  "stream": false,
  "url": false,
  "path": false,
  "util": false,
  "http": false,
    "https": false,
    "os": false,
    "net" : false,
    "tls": false,
    "assert": false,
    "atob": false,
    "btoa": false,
    "canvas": false,
    "gl": false,
    "jsdom": false,
    "mathjax": false,
    "tmp": false,
    "xhr": false,
    "xhr2": false,
    "child_process": false
},
```

This should ignore the specified modules _only_ when webpack tries to bundle for the browser. Otherwise, I get errors like this because these modules only work with node:

```
Module not found: Error: Can't resolve 'path' in '/home/fawadali/personal/projects/jsroot/node_modules/zstd-codec/lib'
```

**Comment by linev** [comment]
Can you make PR?

**Comment by linev** [comment]
Sorry - I did not get your last point.
Recent JSROOT do not require to-level `await`.
Also `"browser"` field in package.json configured as you want. 

That is missing?

**Comment by 9inpachi** [comment]
Another one. Wow. That's a month old.

**Pull request merged**
